$schema: 'https://json-schema.org/draft/2020-12/schema'
properties:
  prefix:
    description: The source code before the caret.
    type: string
    minLength: 1
  suffix:
    description: The source code after the caret.
    type: string
    minLength: 1
  filepath:
    description: The relative path of the file, where completion is requested, with filename and extension.
    type: string
    minLength: 1
  context:
    type: array
    items:
      $ref: '#/$defs/ContextItem'
    default: []
required: [ prefix, suffix, filepath, context ]
$defs:
  ContextItem:
    type: object
    properties:
      type:
        type: string
      filepath:
        type: string
      content:
        type: string
    required: [ type, filepath, content ]
