$schema: 'https://json-schema.org/draft/2020-12/schema'
properties:
  text:
    type: string
    description: A text from the AI agents side to which the model should give an answer.
required:
  - text
