$schema: 'https://json-schema.org/draft/2020-12/schema'
properties:
  prefix:
    description: The source code before the caret.
    type: string
  suffix:
    description: The source code after the caret.
    type: string
  language:
    description: The code language.
    type: string
    enum: [ KOTLIN, JAVA, PYTHON, HCL, OTHER ]
  filepath:
    description: The relative path of the file, where completion is requested, with filename and extension.
    type: string
  multilineAllowed:
    description: Whether multi-line completion is allowed.
    type: boolean
  context:
    type: array
    items:
      $ref: '#/$defs/ContextItem'
    default: [ ]
  explicit:
    type: boolean
    default: true
  useControlModel:
    description: The control mode.
    type: string
    enum: [ "ON", "OFF", "SILENT"]
  generateIndents:
    type: boolean
    default: false
  useCloneFinder:
    type: boolean
    default: false
required: [ prefix, suffix, language, filepath, context, multilineAllowed, explicit, useControlModel, generateIndents, useCloneFinder ]
$defs:
  ContextItem:
    type: object
    properties:
      type:
        type: string
      filepath:
        type: string
      content:
        type: string
    required: [ type, filepath, content ]
