/*     */ package com.intellij.ml.llm.matterhorn.ej.core;
/*     */ 
/*     */ import com.intellij.ml.llm.matterhorn.ej.core.actions.CreateFileAgentAction;
/*     */ import com.intellij.ml.llm.matterhorn.ej.core.actions.GetFileStructureAction;
/*     */ import com.intellij.ml.llm.matterhorn.ej.core.actions.GotoLineAgentAction;
/*     */ import com.intellij.ml.llm.matterhorn.ej.core.actions.OpenEntireFileAgentAction;
/*     */ import com.intellij.ml.llm.matterhorn.ej.core.actions.OpenFileAgentAction;
/*     */ import com.intellij.ml.llm.matterhorn.ej.core.actions.ScrollDownAgentAction;
/*     */ import com.intellij.ml.llm.matterhorn.ej.core.actions.ScrollUpAgentAction;
/*     */ import com.intellij.ml.llm.matterhorn.ej.core.actions.SearchProjectAction;
/*     */ import com.intellij.ml.llm.matterhorn.ej.core.actions.SubmitAgentAction;
/*     */ import com.intellij.ml.llm.matterhorn.ej.core.actions.UndoEditAction;
/*     */ import com.intellij.ml.llm.matterhorn.ej.core.actions.edit.AbstractEditAction;
/*     */ import com.intellij.ml.llm.matterhorn.ej.core.actions.edit.EditAgentAction;
/*     */ import com.intellij.ml.llm.matterhorn.ej.core.actions.edit.EditSearchReplace;
/*     */ import com.intellij.ml.llm.matterhorn.ej.core.actions.edit.EditSubagentAction;
/*     */ import com.intellij.ml.llm.matterhorn.ej.core.actions.edit.RewriteFileAction;
/*     */ import com.intellij.ml.llm.matterhorn.ej.core.actions.tools.BashToolAction;
/*     */ import com.intellij.ml.llm.matterhorn.ej.core.actions.tools.CreateFileToolAction;
/*     */ import com.intellij.ml.llm.matterhorn.ej.core.actions.tools.SearchProjectToolAction;
/*     */ import com.intellij.ml.llm.matterhorn.ej.core.actions.tools.SearchReplaceToolAction;
/*     */ import com.intellij.ml.llm.matterhorn.llm.ModelParameters;
/*     */ import java.util.List;
/*     */ import kotlin.Metadata;
/*     */ import kotlin.collections.CollectionsKt;
/*     */ import kotlin.jvm.internal.Intrinsics;
/*     */ import org.jetbrains.annotations.NotNull;
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ @Metadata(mv = {2, 1, 0}, k = 1, xi = 48, d1 = {"\000$\n\002\030\002\n\002\020\000\n\002\b\003\n\002\020 \n\002\030\002\n\000\n\002\030\002\n\000\n\002\030\002\n\002\b\003\bÆ\002\030\0002\0020\001B\t\b\002¢\006\004\b\002\020\003J\"\020\004\032\b\022\004\022\0020\0060\0052\f\020\007\032\b\022\004\022\0020\b0\0052\006\020\t\032\0020\nJ\"\020\013\032\b\022\004\022\0020\0060\0052\f\020\f\032\b\022\004\022\0020\b0\0052\006\020\t\032\0020\n¨\006\r"}, d2 = {"Lcom/intellij/ml/llm/matterhorn/ej/core/DefaultSingleStepAgent;", "", "<init>", "()V", "getAvailableActions", "", "Lcom/intellij/ml/llm/matterhorn/ej/core/AgentAction;", "errorCheckers", "Lcom/intellij/ml/llm/matterhorn/ej/core/actions/edit/checks/ErrorChecker;", "parameters", "Lcom/intellij/ml/llm/matterhorn/ej/core/AgentParameters;", "getHiddenActions", "errorChecker", "ej-core"})
/*     */ public final class DefaultSingleStepAgent
/*     */ {
/*     */   @NotNull
/*     */   public static final DefaultSingleStepAgent INSTANCE = new DefaultSingleStepAgent();
/*     */   
/*     */   @NotNull
/*     */   public final List<AgentAction> getAvailableActions(@NotNull List errorCheckers, @NotNull AgentParameters parameters) {
/* 768 */     Intrinsics.checkNotNullParameter(errorCheckers, "errorCheckers"); Intrinsics.checkNotNullParameter(parameters, "parameters"); AgentAction editAction = 
/* 769 */       parameters.getUseEditSubagent() ? (AgentAction)new EditSubagentAction() : (
/* 770 */       parameters.getUseTools() ? (AgentAction)new SearchReplaceToolAction(errorCheckers) : 
/* 771 */       (AgentAction)new EditSearchReplace(errorCheckers, true));
/*     */     
/* 773 */     CreateFileAgentAction createAction = 
/* 774 */       parameters.getUseTools() ? (CreateFileAgentAction)new CreateFileToolAction(errorCheckers) : 
/* 775 */       new CreateFileAgentAction(errorCheckers);
/*     */     
/* 777 */     SearchProjectAction searchProjectAction = 
/* 778 */       parameters.getUseTools() ? (SearchProjectAction)new SearchProjectToolAction() : 
/* 779 */       new SearchProjectAction();
/*     */ 
/*     */     
/* 782 */     AgentAction[] arrayOfAgentAction = new AgentAction[11]; arrayOfAgentAction[0] = (AgentAction)searchProjectAction; arrayOfAgentAction[1] = 
/* 783 */       (AgentAction)new GetFileStructureAction();
/* 784 */     arrayOfAgentAction[2] = (AgentAction)new OpenFileAgentAction();
/* 785 */     arrayOfAgentAction[3] = (AgentAction)new OpenEntireFileAgentAction();
/* 786 */     arrayOfAgentAction[4] = (AgentAction)new GotoLineAgentAction();
/* 787 */     arrayOfAgentAction[5] = (AgentAction)new ScrollDownAgentAction();
/* 788 */     arrayOfAgentAction[6] = (AgentAction)new ScrollUpAgentAction();
/* 789 */     arrayOfAgentAction[7] = (AgentAction)createAction;
/* 790 */     arrayOfAgentAction[8] = editAction;
/* 791 */     arrayOfAgentAction[9] = (AgentAction)new UndoEditAction();
/* 792 */     arrayOfAgentAction[10] = (AgentAction)new SubmitAgentAction();
/*     */     List<AgentAction> actions = CollectionsKt.listOf((Object[])arrayOfAgentAction);
/* 794 */     return 
/* 795 */       parameters.getUseTools() ? CollectionsKt.plus(CollectionsKt.listOf(new BashToolAction("bash_20241022")), actions) : 
/* 796 */       actions;
/*     */   }
/*     */   
/*     */   @NotNull
/*     */   public final List<AgentAction> getHiddenActions(@NotNull List errorChecker, @NotNull AgentParameters parameters) {
/* 801 */     Intrinsics.checkNotNullParameter(errorChecker, "errorChecker"); Intrinsics.checkNotNullParameter(parameters, "parameters"); if (ModelParameters.Companion.isAnthropic(parameters.getModelParameters())) {
/* 802 */       return CollectionsKt.emptyList();
/*     */     }
/*     */     
/* 805 */     AbstractEditAction[] arrayOfAbstractEditAction = new AbstractEditAction[3]; arrayOfAbstractEditAction[0] = (AbstractEditAction)new EditSearchReplace(errorChecker, false); arrayOfAbstractEditAction[1] = 
/* 806 */       (AbstractEditAction)new EditAgentAction(errorChecker);
/* 807 */     arrayOfAbstractEditAction[2] = (AbstractEditAction)new RewriteFileAction(errorChecker);
/*     */     return CollectionsKt.listOf((Object[])arrayOfAbstractEditAction);
/*     */   }
/*     */ }


/* Location:              C:\Users\yuzum\Downloads\ej-release-243.132.63.zip!\ej\lib\ej-243.132.63.jar!\com\intellij\ml\llm\matterhorn\ej\core\DefaultSingleStepAgent.class
 * Java compiler version: 17 (61.0)
 * JD-Core Version:       1.1.3
 */