/*   */ package ai.grazie.tone;
/*   */ 
/*   */ @Deprecated(message = "This synthesized declaration should not be used directly", replaceWith = @ReplaceWith(expression = "", imports = {}), level = DeprecationLevel.HIDDEN)
/*   */ @Metadata(mv = {1, 7, 0}, k = 1, xi = 48, d1 = {"\0006\n\000\n\002\030\002\n\002\030\002\n\002\b\002\n\002\030\002\n\002\b\003\n\002\020\021\n\002\030\002\n\002\b\003\n\002\030\002\n\000\n\002\020\002\n\000\n\002\030\002\n\002\b\002\bÇ\002\030\0002\b\022\004\022\0020\0020\001B\007\b\002¢\006\002\020\003J\030\020\b\032\f\022\b\022\006\022\002\b\0030\n0\tHÖ\001¢\006\002\020\013J\021\020\f\032\0020\0022\006\020\r\032\0020\016HÖ\001J\031\020\017\032\0020\0202\006\020\021\032\0020\0222\006\020\023\032\0020\002HÖ\001R\024\020\004\032\0020\0058VXÖ\005¢\006\006\032\004\b\006\020\007¨\006\024"}, d2 = {"ai/grazie/tone/FormalityPrediction.$serializer", "Lkotlinx/serialization/internal/GeneratedSerializer;", "Lai/grazie/tone/FormalityPrediction;", "()V", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "childSerializers", "", "Lkotlinx/serialization/KSerializer;", "()[Lkotlinx/serialization/KSerializer;", "deserialize", "decoder", "Lkotlinx/serialization/encoding/Decoder;", "serialize", "", "encoder", "Lkotlinx/serialization/encoding/Encoder;", "value", "model-tone-formality"})
/*   */ public final class $serializer implements GeneratedSerializer<FormalityPrediction> {
/*   */   @NotNull
/* 7 */   public static final $serializer INSTANCE = new $serializer(); @NotNull public KSerializer<?>[] typeParametersSerializers() { return (KSerializer<?>[])GeneratedSerializer.DefaultImpls.typeParametersSerializers(this); } @NotNull public SerialDescriptor getDescriptor() { return (SerialDescriptor)descriptor; } @NotNull public KSerializer<?>[] childSerializers() { KSerializer[] arrayOfKSerializer = new KSerializer[2]; arrayOfKSerializer[0] = (KSerializer)SentenceFormalityToneSerializer.INSTANCE; arrayOfKSerializer[1] = BuiltinSerializersKt.getNullable((KSerializer)DoubleSerializer.INSTANCE); return (KSerializer<?>[])arrayOfKSerializer; } @NotNull public FormalityPrediction deserialize(@NotNull Decoder decoder) { Intrinsics.checkNotNullParameter(decoder, "decoder"); SerialDescriptor serialDescriptor = getDescriptor(); boolean bool = true; int i = 0; SentenceFormalityTone sentenceFormalityTone = null; Double double_ = null; CompositeDecoder compositeDecoder = decoder.beginStructure(serialDescriptor); if (compositeDecoder.decodeSequentially()) { sentenceFormalityTone = (SentenceFormalityTone)compositeDecoder.decodeSerializableElement(serialDescriptor, 0, (DeserializationStrategy)SentenceFormalityToneSerializer.INSTANCE, sentenceFormalityTone); i |= 0x1; double_ = (Double)compositeDecoder.decodeNullableSerializableElement(serialDescriptor, 1, (DeserializationStrategy)DoubleSerializer.INSTANCE, double_); i |= 0x2; } else { while (bool) { int j = compositeDecoder.decodeElementIndex(serialDescriptor); switch (j) { case -1: bool = false; continue;case 0: sentenceFormalityTone = (SentenceFormalityTone)compositeDecoder.decodeSerializableElement(serialDescriptor, 0, (DeserializationStrategy)SentenceFormalityToneSerializer.INSTANCE, sentenceFormalityTone); i |= 0x1; continue;case 1: double_ = (Double)compositeDecoder.decodeNullableSerializableElement(serialDescriptor, 1, (DeserializationStrategy)DoubleSerializer.INSTANCE, double_); i |= 0x2; continue; }  throw new UnknownFieldException(j); }  }  compositeDecoder.endStructure(serialDescriptor); return new FormalityPrediction(i, sentenceFormalityTone, double_, null); } public void serialize(@NotNull Encoder encoder, @NotNull FormalityPrediction value) { Intrinsics.checkNotNullParameter(encoder, "encoder"); Intrinsics.checkNotNullParameter(value, "value"); SerialDescriptor serialDescriptor = getDescriptor(); CompositeEncoder compositeEncoder = encoder.beginStructure(serialDescriptor); FormalityPrediction.write$Self$model_tone_formality(value, compositeEncoder, serialDescriptor); compositeEncoder.endStructure(serialDescriptor); } static { PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("ai.grazie.tone.FormalityPrediction", INSTANCE, 2); pluginGeneratedSerialDescriptor.addElement("tone", false); pluginGeneratedSerialDescriptor.addElement("score", true); descriptor = pluginGeneratedSerialDescriptor; }
/*   */ 
/*   */ }


/* Location:              C:\Users\yuzum\Downloads\ej-release-243.132.63.zip!\ej\lib\model-tone-formality-jvm-0.4.32.jar!\ai\grazie\tone\FormalityPrediction$$serializer.class
 * Java compiler version: 17 (61.0)
 * JD-Core Version:       1.1.3
 */