/*      */ package org.jetbrains.jewel.ui.icons;
/*      */ 
/*      */ import androidx.compose.runtime.internal.StabilityInferred;
/*      */ import kotlin.Metadata;
/*      */ import org.jetbrains.annotations.NotNull;
/*      */ import org.jetbrains.jewel.ui.icon.IntelliJIconKey;
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ @Metadata(mv = {2, 0, 0}, k = 1, xi = 48, d1 = {"\000\024\n\002\030\002\n\002\020\000\n\002\b\003\n\002\030\002\n\002\b3\bÇ\002\030\0002\0020\001B\t\b\002¢\006\004\b\002\020\003R\021\020\004\032\0020\005¢\006\b\n\000\032\004\b\006\020\007R\021\020\b\032\0020\005¢\006\b\n\000\032\004\b\t\020\007R\021\020\n\032\0020\005¢\006\b\n\000\032\004\b\013\020\007R\021\020\f\032\0020\005¢\006\b\n\000\032\004\b\r\020\007R\021\020\016\032\0020\005¢\006\b\n\000\032\004\b\017\020\007R\021\020\020\032\0020\005¢\006\b\n\000\032\004\b\021\020\007R\021\020\022\032\0020\005¢\006\b\n\000\032\004\b\023\020\007R\021\020\024\032\0020\005¢\006\b\n\000\032\004\b\025\020\007R\021\020\026\032\0020\005¢\006\b\n\000\032\004\b\027\020\007R\021\020\030\032\0020\005¢\006\b\n\000\032\004\b\031\020\007R\021\020\032\032\0020\005¢\006\b\n\000\032\004\b\033\020\007R\021\020\034\032\0020\005¢\006\b\n\000\032\004\b\035\020\007R\021\020\036\032\0020\005¢\006\b\n\000\032\004\b\037\020\007R\021\020 \032\0020\005¢\006\b\n\000\032\004\b!\020\007R\021\020\"\032\0020\005¢\006\b\n\000\032\004\b#\020\007R\021\020$\032\0020\005¢\006\b\n\000\032\004\b%\020\007R\021\020&\032\0020\005¢\006\b\n\000\032\004\b'\020\007R\021\020(\032\0020\005¢\006\b\n\000\032\004\b)\020\007R\021\020*\032\0020\005¢\006\b\n\000\032\004\b+\020\007R\021\020,\032\0020\005¢\006\b\n\000\032\004\b-\020\007R\021\020.\032\0020\005¢\006\b\n\000\032\004\b/\020\007R\021\0200\032\0020\005¢\006\b\n\000\032\004\b1\020\007R\021\0202\032\0020\005¢\006\b\n\000\032\004\b3\020\007R\021\0204\032\0020\005¢\006\b\n\000\032\004\b5\020\007R\021\0206\032\0020\005¢\006\b\n\000\032\004\b7\020\007¨\0068"}, d2 = {"Lorg/jetbrains/jewel/ui/icons/AllIconsKeys$Diff;", "", "<init>", "()V", "ApplyNotConflicts", "Lorg/jetbrains/jewel/ui/icon/IntelliJIconKey;", "getApplyNotConflicts", "()Lorg/jetbrains/jewel/ui/icon/IntelliJIconKey;", "ApplyNotConflictsLeft", "getApplyNotConflictsLeft", "ApplyNotConflictsRight", "getApplyNotConflictsRight", "Arrow", "getArrow", "ArrowLeftDown", "getArrowLeftDown", "ArrowLeftRight", "getArrowLeftRight", "ArrowRight", "getArrowRight", "ArrowRightDown", "getArrowRightDown", "Compare3LeftMiddle", "getCompare3LeftMiddle", "Compare3LeftRight", "getCompare3LeftRight", "Compare3MiddleRight", "getCompare3MiddleRight", "Compare4LeftBottom", "getCompare4LeftBottom", "Compare4LeftMiddle", "getCompare4LeftMiddle", "Compare4LeftRight", "getCompare4LeftRight", "Compare4MiddleBottom", "getCompare4MiddleBottom", "Compare4MiddleRight", "getCompare4MiddleRight", "Compare4RightBottom", "getCompare4RightBottom", "GutterCheckBox", "getGutterCheckBox", "GutterCheckBoxIndeterminate", "getGutterCheckBoxIndeterminate", "GutterCheckBoxSelected", "getGutterCheckBoxSelected", "Lock", "getLock", "MagicResolve", "getMagicResolve", "MagicResolveToolbar", "getMagicResolveToolbar", "Remove", "getRemove", "Revert", "getRevert", "ui"})
/*      */ @StabilityInferred(parameters = 0)
/*      */ public final class Diff
/*      */ {
/*      */   @NotNull
/*      */   public final IntelliJIconKey getApplyNotConflicts() {
/* 1167 */     return ApplyNotConflicts; } @NotNull
/* 1168 */   public static final Diff INSTANCE = new Diff(); @NotNull private static final IntelliJIconKey ApplyNotConflicts = new IntelliJIconKey("diff/applyNotConflicts.svg", "expui/diff/applyNotConflicts.svg", 
/* 1169 */       AllIconsKeys.class);
/*      */   @NotNull
/* 1171 */   public final IntelliJIconKey getApplyNotConflictsLeft() { return ApplyNotConflictsLeft; } @NotNull
/* 1172 */   private static final IntelliJIconKey ApplyNotConflictsLeft = new IntelliJIconKey("diff/applyNotConflictsLeft.svg", 
/* 1173 */       "expui/diff/applyNotConflictsLeft.svg", AllIconsKeys.class);
/*      */   @NotNull
/* 1175 */   public final IntelliJIconKey getApplyNotConflictsRight() { return ApplyNotConflictsRight; } @NotNull
/* 1176 */   private static final IntelliJIconKey ApplyNotConflictsRight = new IntelliJIconKey("diff/applyNotConflictsRight.svg", 
/* 1177 */       "expui/diff/applyNotConflictsRight.svg", AllIconsKeys.class);
/*      */   @NotNull
/* 1179 */   private static final IntelliJIconKey Arrow = new IntelliJIconKey("diff/arrow.svg", 
/* 1180 */       "expui/diff/arrow@14x14.svg", AllIconsKeys.class); @NotNull public final IntelliJIconKey getArrow() { return Arrow; }
/*      */   @NotNull
/* 1182 */   private static final IntelliJIconKey ArrowLeftDown = new IntelliJIconKey("diff/arrowLeftDown.svg", 
/* 1183 */       "expui/diff/arrowLeftDown@14x14.svg", AllIconsKeys.class); @NotNull public final IntelliJIconKey getArrowLeftDown() { return ArrowLeftDown; }
/*      */   @NotNull
/* 1185 */   private static final IntelliJIconKey ArrowLeftRight = new IntelliJIconKey("diff/arrowLeftRight.svg", 
/* 1186 */       "expui/diff/arrowLeftRight.svg", AllIconsKeys.class); @NotNull public final IntelliJIconKey getArrowLeftRight() { return ArrowLeftRight; }
/*      */   @NotNull
/* 1188 */   private static final IntelliJIconKey ArrowRight = new IntelliJIconKey("diff/arrowRight.svg", 
/* 1189 */       "expui/diff/arrowRight@14x14.svg", AllIconsKeys.class); @NotNull public final IntelliJIconKey getArrowRight() { return ArrowRight; }
/*      */   @NotNull
/* 1191 */   private static final IntelliJIconKey ArrowRightDown = new IntelliJIconKey("diff/arrowRightDown.svg", 
/* 1192 */       "expui/diff/arrowRightDown@14x14.svg", AllIconsKeys.class);
/*      */   @NotNull
/* 1194 */   public final IntelliJIconKey getCompare3LeftMiddle() { return Compare3LeftMiddle; }
/* 1195 */   @NotNull public final IntelliJIconKey getArrowRightDown() { return ArrowRightDown; } @NotNull private static final IntelliJIconKey Compare3LeftMiddle = new IntelliJIconKey("diff/compare3LeftMiddle.svg", "expui/diff/compare3LeftMiddle.svg", 
/* 1196 */       AllIconsKeys.class);
/*      */   @NotNull
/* 1198 */   public final IntelliJIconKey getCompare3LeftRight() { return Compare3LeftRight; } @NotNull
/* 1199 */   private static final IntelliJIconKey Compare3LeftRight = new IntelliJIconKey("diff/compare3LeftRight.svg", "expui/diff/compare3LeftRight.svg", 
/* 1200 */       AllIconsKeys.class);
/*      */   @NotNull
/* 1202 */   public final IntelliJIconKey getCompare3MiddleRight() { return Compare3MiddleRight; } @NotNull
/* 1203 */   private static final IntelliJIconKey Compare3MiddleRight = new IntelliJIconKey("diff/compare3MiddleRight.svg", 
/* 1204 */       "expui/diff/compare3MiddleRight.svg", AllIconsKeys.class);
/*      */   @NotNull
/* 1206 */   public final IntelliJIconKey getCompare4LeftBottom() { return Compare4LeftBottom; } @NotNull
/* 1207 */   private static final IntelliJIconKey Compare4LeftBottom = new IntelliJIconKey("diff/compare4LeftBottom.svg", "expui/diff/compare4LeftBottom.svg", 
/* 1208 */       AllIconsKeys.class);
/*      */   @NotNull
/* 1210 */   public final IntelliJIconKey getCompare4LeftMiddle() { return Compare4LeftMiddle; } @NotNull
/* 1211 */   private static final IntelliJIconKey Compare4LeftMiddle = new IntelliJIconKey("diff/compare4LeftMiddle.svg", "expui/diff/compare4LeftMiddle.svg", 
/* 1212 */       AllIconsKeys.class);
/*      */   @NotNull
/* 1214 */   public final IntelliJIconKey getCompare4LeftRight() { return Compare4LeftRight; } @NotNull
/* 1215 */   private static final IntelliJIconKey Compare4LeftRight = new IntelliJIconKey("diff/compare4LeftRight.svg", "expui/diff/compare4LeftRight.svg", 
/* 1216 */       AllIconsKeys.class);
/*      */   @NotNull
/* 1218 */   public final IntelliJIconKey getCompare4MiddleBottom() { return Compare4MiddleBottom; } @NotNull
/* 1219 */   private static final IntelliJIconKey Compare4MiddleBottom = new IntelliJIconKey("diff/compare4MiddleBottom.svg", 
/* 1220 */       "expui/diff/compare4MiddleBottom.svg", AllIconsKeys.class);
/*      */   @NotNull
/* 1222 */   public final IntelliJIconKey getCompare4MiddleRight() { return Compare4MiddleRight; } @NotNull
/* 1223 */   private static final IntelliJIconKey Compare4MiddleRight = new IntelliJIconKey("diff/compare4MiddleRight.svg", 
/* 1224 */       "expui/diff/compare4MiddleRight.svg", AllIconsKeys.class);
/*      */   @NotNull
/* 1226 */   public final IntelliJIconKey getCompare4RightBottom() { return Compare4RightBottom; } @NotNull
/* 1227 */   private static final IntelliJIconKey Compare4RightBottom = new IntelliJIconKey("diff/compare4RightBottom.svg", 
/* 1228 */       "expui/diff/compare4RightBottom.svg", AllIconsKeys.class);
/*      */   @NotNull
/* 1230 */   private static final IntelliJIconKey GutterCheckBox = new IntelliJIconKey("diff/gutterCheckBox.svg", 
/* 1231 */       "expui/diff/gutterCheckBox@14x14.svg", AllIconsKeys.class); @NotNull public final IntelliJIconKey getGutterCheckBox() { return GutterCheckBox; }
/*      */   @NotNull
/* 1233 */   public final IntelliJIconKey getGutterCheckBoxIndeterminate() { return GutterCheckBoxIndeterminate; } @NotNull
/* 1234 */   private static final IntelliJIconKey GutterCheckBoxIndeterminate = new IntelliJIconKey("diff/gutterCheckBoxIndeterminate.svg", 
/* 1235 */       "expui/diff/gutterCheckBoxIndeterminate@14x14.svg", AllIconsKeys.class);
/*      */   @NotNull
/* 1237 */   public final IntelliJIconKey getGutterCheckBoxSelected() { return GutterCheckBoxSelected; } @NotNull
/* 1238 */   private static final IntelliJIconKey GutterCheckBoxSelected = new IntelliJIconKey("diff/gutterCheckBoxSelected.svg", 
/* 1239 */       "expui/diff/gutterCheckBoxSelected@14x14.svg", AllIconsKeys.class);
/*      */   @NotNull
/* 1241 */   private static final IntelliJIconKey Lock = new IntelliJIconKey("diff/lock.svg", 
/* 1242 */       "expui/diff/disableEditing.svg", AllIconsKeys.class); @NotNull public final IntelliJIconKey getLock() { return Lock; }
/*      */   @NotNull
/* 1244 */   private static final IntelliJIconKey MagicResolve = new IntelliJIconKey("diff/magicResolve.svg", 
/* 1245 */       "expui/diff/magicResolve@14x14.svg", AllIconsKeys.class); @NotNull public final IntelliJIconKey getMagicResolve() { return MagicResolve; }
/*      */   @NotNull
/* 1247 */   public final IntelliJIconKey getMagicResolveToolbar() { return MagicResolveToolbar; } @NotNull
/* 1248 */   private static final IntelliJIconKey MagicResolveToolbar = new IntelliJIconKey("diff/magicResolveToolbar.svg", 
/* 1249 */       "expui/diff/magicResolveToolbar.svg", AllIconsKeys.class);
/*      */   @NotNull
/* 1251 */   private static final IntelliJIconKey Remove = new IntelliJIconKey("diff/remove.svg", 
/* 1252 */       "expui/diff/remove@14x14.svg", AllIconsKeys.class); @NotNull public final IntelliJIconKey getRemove() { return Remove; }
/*      */   @NotNull
/* 1254 */   private static final IntelliJIconKey Revert = new IntelliJIconKey("diff/revert.svg", 
/* 1255 */       "expui/diff/revert@14x14.svg", AllIconsKeys.class);
/*      */   public static final int $stable = 8;
/*      */   
/*      */   @NotNull
/*      */   public final IntelliJIconKey getRevert() {
/*      */     return Revert;
/*      */   }
/*      */ }


/* Location:              C:\Users\yuzum\Downloads\ej-release-243.132.63.zip!\ej\lib\jewel-ui-243-0.27.0.jar!\org\jetbrains\jewe\\ui\icons\AllIconsKeys$Diff.class
 * Java compiler version: 17 (61.0)
 * JD-Core Version:       1.1.3
 */