/*     */ package org.jetbrains.jewel.ui.component;
/*     */ 
/*     */ import androidx.compose.foundation.interaction.Interaction;
/*     */ import androidx.compose.runtime.MutableState;
/*     */ import kotlin.Metadata;
/*     */ import kotlin.Unit;
/*     */ import kotlin.coroutines.Continuation;
/*     */ import kotlinx.coroutines.flow.FlowCollector;
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ @Metadata(mv = {2, 0, 0}, k = 3, xi = 48)
/*     */ final class null<T>
/*     */   implements FlowCollector
/*     */ {
/*     */   public final Object emit(Interaction interaction, Continuation $completion) {
/* 329 */     Interaction interaction1 = interaction;
/* 330 */     if (interaction1 instanceof androidx.compose.foundation.interaction.PressInteraction.Press || 
/* 331 */       interaction1 instanceof androidx.compose.foundation.interaction.DragInteraction.Start) { SliderKt.access$SliderThumb_RfXq3Jk$lambda$18$lambda$15(this.$state$delegate, SliderState.copy-GPhM_18$default(SliderKt.access$SliderThumb_RfXq3Jk$lambda$18$lambda$14(this.$state$delegate), false, false, true, false, false, 27, null)); }
/*     */     
/* 333 */     else if (interaction1 instanceof androidx.compose.foundation.interaction.PressInteraction.Release || 
/* 334 */       interaction1 instanceof androidx.compose.foundation.interaction.PressInteraction.Cancel || 
/* 335 */       interaction1 instanceof androidx.compose.foundation.interaction.DragInteraction.Stop || 
/* 336 */       interaction1 instanceof androidx.compose.foundation.interaction.DragInteraction.Cancel) { SliderKt.access$SliderThumb_RfXq3Jk$lambda$18$lambda$15(this.$state$delegate, SliderState.copy-GPhM_18$default(SliderKt.access$SliderThumb_RfXq3Jk$lambda$18$lambda$14(this.$state$delegate), false, false, false, false, false, 27, null)); }
/*     */     
/* 338 */     else if (interaction1 instanceof androidx.compose.foundation.interaction.HoverInteraction.Enter) { SliderKt.access$SliderThumb_RfXq3Jk$lambda$18$lambda$15(this.$state$delegate, SliderState.copy-GPhM_18$default(SliderKt.access$SliderThumb_RfXq3Jk$lambda$18$lambda$14(this.$state$delegate), false, false, false, true, false, 23, null)); }
/* 339 */     else if (interaction1 instanceof androidx.compose.foundation.interaction.HoverInteraction.Exit) { SliderKt.access$SliderThumb_RfXq3Jk$lambda$18$lambda$15(this.$state$delegate, SliderState.copy-GPhM_18$default(SliderKt.access$SliderThumb_RfXq3Jk$lambda$18$lambda$14(this.$state$delegate), false, false, false, false, false, 23, null)); }
/* 340 */     else if (interaction1 instanceof androidx.compose.foundation.interaction.FocusInteraction.Focus) { SliderKt.access$SliderThumb_RfXq3Jk$lambda$18$lambda$15(this.$state$delegate, SliderState.copy-GPhM_18$default(SliderKt.access$SliderThumb_RfXq3Jk$lambda$18$lambda$14(this.$state$delegate), false, true, false, false, false, 29, null)); }
/* 341 */     else if (interaction1 instanceof androidx.compose.foundation.interaction.FocusInteraction.Unfocus) { SliderKt.access$SliderThumb_RfXq3Jk$lambda$18$lambda$15(this.$state$delegate, SliderState.copy-GPhM_18$default(SliderKt.access$SliderThumb_RfXq3Jk$lambda$18$lambda$14(this.$state$delegate), false, false, false, false, false, 29, null)); }
/*     */     
/* 343 */     return Unit.INSTANCE;
/*     */   }
/*     */   
/*     */   null(MutableState<SliderState> $state$delegate) {}
/*     */ }


/* Location:              C:\Users\yuzum\Downloads\ej-release-243.132.63.zip!\ej\lib\jewel-ui-243-0.27.0.jar!\org\jetbrains\jewe\\ui\component\SliderKt$SliderThumb$1$2$1$1.class
 * Java compiler version: 17 (61.0)
 * JD-Core Version:       1.1.3
 */